# _config.yml
title: Tal's Tech Corner
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog by Tal, a software engineer and mobile developer.
  Get insights into mobile development, software engineering, and life in Canada.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: your_twitter_handle
github_username: your_github_handle

collections:
  blog1:
    output: true
    permalink: /blog1/:title
  blog2:
    output: true
    permalink: /blog2/:title
  blog3:
    output: true
    permalink: /blog3/:title
